config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "posts#index", as: 'home'
get 'about' => "pages#about", as: 'about'

resources :posts do
  resources :comments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "1234"
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = "ИНФА"
    @maintext = "Здесь будет написано о сервисе. Что конкретно- пока не известно. Но это уже и не так важно. Главное- написать, а там додумаем ;)"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @heading = "ГЛАГНЕ"
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

def update
  @post = Post.find(params[:id])
  if(@post.update(post_params))
  redirect_to @post
else
  render 'edit'
end
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path
end

  def create
    @post = Post.new(post_params)

    if(@post.save)
    redirect_to @post
  else
    render 'new'
  end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tourreview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">TourReview</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark"><%= link_to "Главная", home_path %></span>
        <span class="p-2 text-dark"><%= link_to "О проекте", about_path %></span>
      </nav>
      <span class="btn btn-outline-primary"><%= link_to "Оставить отзыв", new_post_path %></span>
    </div>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><center>
  <%= @heading %>
</center></h1>
<p><center>
  <%= @maintext %>
</center></p>

app/views/posts/edit.html.erb
<h2>Редактирование отзыва</h2>

  <%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <div class ="alert alert-danger"><%= msg %></div>
  <%end %>
  <% end %>
<p>
  Название заведения<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Текст отзыва<br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p> <%= f.submit({:class => 'btn btn-success'}) %> </p>
<% end %>
</center>

app/views/posts/index.html.erb
<h1>
  <%= @heading %>
</h1>


  <% @post.each do |post| %>
  <div class="alert alert-light">
  <h3><%= post.title %></h3>
  <p><%= post.body %></p>
  <%= link_to "Читать далее", post_path(post), :class => 'btn btn-outline-primary'%>
  </div>
  <% end %>

app/views/posts/new.html.erb
<h2>Создание нового отзыва</h2>

  <%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <div class ="alert alert-danger"><%= msg %></div>
  <%end %>
  <% end %>
<p>
  Название заведения<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Текст отзыва<br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p> <%= f.submit({:class => 'btn btn-success'}) %> </p>
<% end %>
</center>

app/views/posts/show.html.erb
<center><h1>Кто-то недавно написал вот это:</h1>
  <h3><%= @post.title %></h3>
    <p><%= @post.body %></p>
  </center>
<hr>
<%= link_to "Поменять шота", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Удолить эту гнусную депешу!", post_path(@post), method: :delete,  data: {confirm: "Удолить?"}, :class => 'btn btn-danger' %>
<hr>
<h2>
  А тут у нас мнения пасутся! Такие дела...
</h2>


  <% @post.comments.each do |comment| %>
  <div class="alert alert-light">
<p><strong><%= comment.username %></strong>: <%= comment.body %></p>
  </div>
  <% end %>
<hr>
<h3>Ща напишу как было</h3>

  <%= form_for ([@post, @post.comments.build]) do |f| %>

<p>
  Кто я<br>
  <%= f.text_field(:username, {:class => 'form-control'}) %>
</p>
<p>
  Было так<br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p> <%= f.submit("От теперь правда!", {:class => 'btn btn-warning'}) %> </p>
<% end %>
</center>